# create new portainer container for raspberry pi with docker-compose
# start:    `docker-compose up -d`
# upgrade:  `docker-compose down && docker rm portainer-app && docker-compose up -d`
# address:  [localhost](http://localhost:9000)
# sources:  [github.com](github.com/portainer/portainer-compose.git)
#           [hypriot.com](blog.hypriot.com/post/new-docker-ui-portainer)
# date:     2017-07-01

version: '2'
services:
  portainer:
    image: portainer/portainer:latest
      # using portainer image for raspberry pi by deviantony
      # sources: [github.com](https://github.com/portainer/portainer.git)
    container_name: portainer-app
    volumes:
      # establish connection to docker
      - /var/run/docker.sock:/var/run/docker.sock
      # data directory for this app
      - /home/pi/containers/portainer/data:/data
      # SSL certs for the container
#      - /home/pi/ssl-keys:/certs
    command: --host=unix:///var/run/docker.sock
#    command: --host=unix:///var/run/docker.sock  --ssl --sslcert /certs/piserver.crt --sslkey /certs/piserver.key
    ports:
      # http port
      - "9000:9000"
#      - "443:9000"
    restart: on-failure
    labels:
      - traefik.enable=true
      - "portainer.frontend.rule=Host:portainer.docker.localhost"

