FROM alpine:latest

RUN apk --no-cache add unbound openssl wget dnssec-root

#Debugging
#RUN apk --no-cache add iproute2 bind-tools tcpdump

RUN printf '%s\n' \
    "include: /etc/unbound/conf.d/*.conf" \
    "include: /etc/unbound/local.d/*.conf" \
    | tee -a /etc/unbound/unbound.conf \
    && sed -i '/root-hints:/d' /etc/unbound/unbound.conf

COPY config/unbound/conf.d/  /etc/unbound/conf.d/
COPY config/unbound/local.d/ /etc/unbound/local.d/
COPY entrypoints/unbound.sh  /entrypoint.sh

# Fails somehow?? Maybe because the build is not routing to the internet.
#RUN /etc/periodic/monthly/update-unbound-root-hints
#RUN cd /etc/unbound && wget -O root.hints https://www.internic.net/domain/named.root
COPY config/unbound/root.hints  /etc/unbound/

# Copy unbound files to a place we are not volume mounting so they can be copies back
# by the entrypoint.
RUN mkdir -p /etc/unbound_example && cp -R /etc/unbound/* /etc/unbound_example/

EXPOSE 53/udp 53/tcp

ENTRYPOINT [ "/entrypoint.sh" ]

CMD [ "/usr/sbin/unbound", "-d" ]
